name: Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test.
      run: make test-all
    - name: Run error test.
      run: make err-test-all
    - name: Run driver test.
      run: make driver-test
